# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class enum__Torappu_SharedConsts_Direction(object):
    UP = 0
    RIGHT = 1
    DOWN = 2
    LEFT = 3
    E_NUM = 4
    INVALID = 4
