# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_Torappu_LevelData_BranchData_PhaseData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_Torappu_LevelData_BranchData_PhaseData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_Torappu_LevelData_BranchData_PhaseData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_Torappu_LevelData_BranchData_PhaseData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_Torappu_LevelData_BranchData_PhaseData
    def PreDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # clz_Torappu_LevelData_BranchData_PhaseData
    def Actions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from clz_Torappu_LevelData_WaveData_FragmentData_ActionData import clz_Torappu_LevelData_WaveData_FragmentData_ActionData
            obj = clz_Torappu_LevelData_WaveData_FragmentData_ActionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_LevelData_BranchData_PhaseData
    def ActionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # clz_Torappu_LevelData_BranchData_PhaseData
    def ActionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def clz_Torappu_LevelData_BranchData_PhaseDataStart(builder):
    builder.StartObject(2)

def Start(builder):
    clz_Torappu_LevelData_BranchData_PhaseDataStart(builder)

def clz_Torappu_LevelData_BranchData_PhaseDataAddPreDelay(builder, preDelay):
    builder.PrependFloat32Slot(0, preDelay, 0.0)

def AddPreDelay(builder, preDelay):
    clz_Torappu_LevelData_BranchData_PhaseDataAddPreDelay(builder, preDelay)

def clz_Torappu_LevelData_BranchData_PhaseDataAddActions(builder, actions):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(actions), 0)

def AddActions(builder, actions):
    clz_Torappu_LevelData_BranchData_PhaseDataAddActions(builder, actions)

def clz_Torappu_LevelData_BranchData_PhaseDataStartActionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActionsVector(builder, numElems):
    return clz_Torappu_LevelData_BranchData_PhaseDataStartActionsVector(builder, numElems)

def clz_Torappu_LevelData_BranchData_PhaseDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return clz_Torappu_LevelData_BranchData_PhaseDataEnd(builder)

import clz_Torappu_LevelData_WaveData_FragmentData_ActionData
try:
    from typing import List
except:
    pass

class clz_Torappu_LevelData_BranchData_PhaseDataT(object):

    # clz_Torappu_LevelData_BranchData_PhaseDataT
    def __init__(self):
        self.preDelay = 0.0  # type: float
        self.actions = None  # type: List[clz_Torappu_LevelData_WaveData_FragmentData_ActionData.clz_Torappu_LevelData_WaveData_FragmentData_ActionDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzTorappuLevelDataBranchDataPhaseData = clz_Torappu_LevelData_BranchData_PhaseData()
        clzTorappuLevelDataBranchDataPhaseData.Init(buf, pos)
        return cls.InitFromObj(clzTorappuLevelDataBranchDataPhaseData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzTorappuLevelDataBranchDataPhaseData):
        x = clz_Torappu_LevelData_BranchData_PhaseDataT()
        x._UnPack(clzTorappuLevelDataBranchDataPhaseData)
        return x

    # clz_Torappu_LevelData_BranchData_PhaseDataT
    def _UnPack(self, clzTorappuLevelDataBranchDataPhaseData):
        if clzTorappuLevelDataBranchDataPhaseData is None:
            return
        self.preDelay = clzTorappuLevelDataBranchDataPhaseData.PreDelay()
        if not clzTorappuLevelDataBranchDataPhaseData.ActionsIsNone():
            self.actions = []
            for i in range(clzTorappuLevelDataBranchDataPhaseData.ActionsLength()):
                if clzTorappuLevelDataBranchDataPhaseData.Actions(i) is None:
                    self.actions.append(None)
                else:
                    clz_Torappu_LevelData_WaveData_FragmentData_ActionData_ = clz_Torappu_LevelData_WaveData_FragmentData_ActionData.clz_Torappu_LevelData_WaveData_FragmentData_ActionDataT.InitFromObj(clzTorappuLevelDataBranchDataPhaseData.Actions(i))
                    self.actions.append(clz_Torappu_LevelData_WaveData_FragmentData_ActionData_)

    # clz_Torappu_LevelData_BranchData_PhaseDataT
    def Pack(self, builder):
        if self.actions is not None:
            actionslist = []
            for i in range(len(self.actions)):
                actionslist.append(self.actions[i].Pack(builder))
            clz_Torappu_LevelData_BranchData_PhaseDataStartActionsVector(builder, len(self.actions))
            for i in reversed(range(len(self.actions))):
                builder.PrependUOffsetTRelative(actionslist[i])
            actions = builder.EndVector()
        clz_Torappu_LevelData_BranchData_PhaseDataStart(builder)
        clz_Torappu_LevelData_BranchData_PhaseDataAddPreDelay(builder, self.preDelay)
        if self.actions is not None:
            clz_Torappu_LevelData_BranchData_PhaseDataAddActions(builder, actions)
        clzTorappuLevelDataBranchDataPhaseData = clz_Torappu_LevelData_BranchData_PhaseDataEnd(builder)
        return clzTorappuLevelDataBranchDataPhaseData
