# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class enum__Torappu_LevelData_Difficulty(object):
    NONE = 0
    NORMAL = 1
    FOUR_STAR = 2
    EASY = 4
    ALL = 7
