# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_Torappu_GridPosition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_Torappu_GridPosition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_Torappu_GridPosition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_Torappu_GridPosition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_Torappu_GridPosition
    def Row(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # clz_Torappu_GridPosition
    def Col(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def clz_Torappu_GridPositionStart(builder):
    builder.StartObject(2)

def Start(builder):
    clz_Torappu_GridPositionStart(builder)

def clz_Torappu_GridPositionAddRow(builder, row):
    builder.PrependInt32Slot(0, row, 0)

def AddRow(builder, row):
    clz_Torappu_GridPositionAddRow(builder, row)

def clz_Torappu_GridPositionAddCol(builder, col):
    builder.PrependInt32Slot(1, col, 0)

def AddCol(builder, col):
    clz_Torappu_GridPositionAddCol(builder, col)

def clz_Torappu_GridPositionEnd(builder):
    return builder.EndObject()

def End(builder):
    return clz_Torappu_GridPositionEnd(builder)


class clz_Torappu_GridPositionT(object):

    # clz_Torappu_GridPositionT
    def __init__(self):
        self.row = 0  # type: int
        self.col = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzTorappuGridPosition = clz_Torappu_GridPosition()
        clzTorappuGridPosition.Init(buf, pos)
        return cls.InitFromObj(clzTorappuGridPosition)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzTorappuGridPosition):
        x = clz_Torappu_GridPositionT()
        x._UnPack(clzTorappuGridPosition)
        return x

    # clz_Torappu_GridPositionT
    def _UnPack(self, clzTorappuGridPosition):
        if clzTorappuGridPosition is None:
            return
        self.row = clzTorappuGridPosition.Row()
        self.col = clzTorappuGridPosition.Col()

    # clz_Torappu_GridPositionT
    def Pack(self, builder):
        clz_Torappu_GridPositionStart(builder)
        clz_Torappu_GridPositionAddRow(builder, self.row)
        clz_Torappu_GridPositionAddCol(builder, self.col)
        clzTorappuGridPosition = clz_Torappu_GridPositionEnd(builder)
        return clzTorappuGridPosition
