# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_Torappu_EnemyDatabase_AttributesData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_Torappu_EnemyDatabase_AttributesData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_Torappu_EnemyDatabase_AttributesData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_Torappu_EnemyDatabase_AttributesData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_Torappu_EnemyDatabase_AttributesData
    def MaxHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def Atk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def Def(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def MagicResistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def Cost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def BlockCnt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def MoveSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def AttackSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def BaseAttackTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def RespawnTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def HpRecoveryPerSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def SpRecoveryPerSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def MaxDeployCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def MassLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def BaseForceLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def TauntLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Int32_ import clz_Torappu_Undefinable_1_System_Int32_
            obj = clz_Torappu_Undefinable_1_System_Int32_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def EpDamageResistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def EpResistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def DamageHitratePhysical(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def DamageHitrateMagical(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Single_ import clz_Torappu_Undefinable_1_System_Single_
            obj = clz_Torappu_Undefinable_1_System_Single_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def StunImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def SilenceImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def SleepImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def FrozenImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def LevitateImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def DisarmedCombatImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def FearedImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_EnemyDatabase_AttributesData
    def PalsyImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_Undefinable_1_System_Boolean_ import clz_Torappu_Undefinable_1_System_Boolean_
            obj = clz_Torappu_Undefinable_1_System_Boolean_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def clz_Torappu_EnemyDatabase_AttributesDataStart(builder):
    builder.StartObject(28)

def Start(builder):
    clz_Torappu_EnemyDatabase_AttributesDataStart(builder)

def clz_Torappu_EnemyDatabase_AttributesDataAddMaxHp(builder, maxHp):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(maxHp), 0)

def AddMaxHp(builder, maxHp):
    clz_Torappu_EnemyDatabase_AttributesDataAddMaxHp(builder, maxHp)

def clz_Torappu_EnemyDatabase_AttributesDataAddAtk(builder, atk):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(atk), 0)

def AddAtk(builder, atk):
    clz_Torappu_EnemyDatabase_AttributesDataAddAtk(builder, atk)

def clz_Torappu_EnemyDatabase_AttributesDataAddDef(builder, def_):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(def_), 0)

def AddDef(builder, def_):
    clz_Torappu_EnemyDatabase_AttributesDataAddDef(builder, def_)

def clz_Torappu_EnemyDatabase_AttributesDataAddMagicResistance(builder, magicResistance):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(magicResistance), 0)

def AddMagicResistance(builder, magicResistance):
    clz_Torappu_EnemyDatabase_AttributesDataAddMagicResistance(builder, magicResistance)

def clz_Torappu_EnemyDatabase_AttributesDataAddCost(builder, cost):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(cost), 0)

def AddCost(builder, cost):
    clz_Torappu_EnemyDatabase_AttributesDataAddCost(builder, cost)

def clz_Torappu_EnemyDatabase_AttributesDataAddBlockCnt(builder, blockCnt):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(blockCnt), 0)

def AddBlockCnt(builder, blockCnt):
    clz_Torappu_EnemyDatabase_AttributesDataAddBlockCnt(builder, blockCnt)

def clz_Torappu_EnemyDatabase_AttributesDataAddMoveSpeed(builder, moveSpeed):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(moveSpeed), 0)

def AddMoveSpeed(builder, moveSpeed):
    clz_Torappu_EnemyDatabase_AttributesDataAddMoveSpeed(builder, moveSpeed)

def clz_Torappu_EnemyDatabase_AttributesDataAddAttackSpeed(builder, attackSpeed):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(attackSpeed), 0)

def AddAttackSpeed(builder, attackSpeed):
    clz_Torappu_EnemyDatabase_AttributesDataAddAttackSpeed(builder, attackSpeed)

def clz_Torappu_EnemyDatabase_AttributesDataAddBaseAttackTime(builder, baseAttackTime):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(baseAttackTime), 0)

def AddBaseAttackTime(builder, baseAttackTime):
    clz_Torappu_EnemyDatabase_AttributesDataAddBaseAttackTime(builder, baseAttackTime)

def clz_Torappu_EnemyDatabase_AttributesDataAddRespawnTime(builder, respawnTime):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(respawnTime), 0)

def AddRespawnTime(builder, respawnTime):
    clz_Torappu_EnemyDatabase_AttributesDataAddRespawnTime(builder, respawnTime)

def clz_Torappu_EnemyDatabase_AttributesDataAddHpRecoveryPerSec(builder, hpRecoveryPerSec):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(hpRecoveryPerSec), 0)

def AddHpRecoveryPerSec(builder, hpRecoveryPerSec):
    clz_Torappu_EnemyDatabase_AttributesDataAddHpRecoveryPerSec(builder, hpRecoveryPerSec)

def clz_Torappu_EnemyDatabase_AttributesDataAddSpRecoveryPerSec(builder, spRecoveryPerSec):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(spRecoveryPerSec), 0)

def AddSpRecoveryPerSec(builder, spRecoveryPerSec):
    clz_Torappu_EnemyDatabase_AttributesDataAddSpRecoveryPerSec(builder, spRecoveryPerSec)

def clz_Torappu_EnemyDatabase_AttributesDataAddMaxDeployCount(builder, maxDeployCount):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(maxDeployCount), 0)

def AddMaxDeployCount(builder, maxDeployCount):
    clz_Torappu_EnemyDatabase_AttributesDataAddMaxDeployCount(builder, maxDeployCount)

def clz_Torappu_EnemyDatabase_AttributesDataAddMassLevel(builder, massLevel):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(massLevel), 0)

def AddMassLevel(builder, massLevel):
    clz_Torappu_EnemyDatabase_AttributesDataAddMassLevel(builder, massLevel)

def clz_Torappu_EnemyDatabase_AttributesDataAddBaseForceLevel(builder, baseForceLevel):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(baseForceLevel), 0)

def AddBaseForceLevel(builder, baseForceLevel):
    clz_Torappu_EnemyDatabase_AttributesDataAddBaseForceLevel(builder, baseForceLevel)

def clz_Torappu_EnemyDatabase_AttributesDataAddTauntLevel(builder, tauntLevel):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(tauntLevel), 0)

def AddTauntLevel(builder, tauntLevel):
    clz_Torappu_EnemyDatabase_AttributesDataAddTauntLevel(builder, tauntLevel)

def clz_Torappu_EnemyDatabase_AttributesDataAddEpDamageResistance(builder, epDamageResistance):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(epDamageResistance), 0)

def AddEpDamageResistance(builder, epDamageResistance):
    clz_Torappu_EnemyDatabase_AttributesDataAddEpDamageResistance(builder, epDamageResistance)

def clz_Torappu_EnemyDatabase_AttributesDataAddEpResistance(builder, epResistance):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(epResistance), 0)

def AddEpResistance(builder, epResistance):
    clz_Torappu_EnemyDatabase_AttributesDataAddEpResistance(builder, epResistance)

def clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitratePhysical(builder, damageHitratePhysical):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(damageHitratePhysical), 0)

def AddDamageHitratePhysical(builder, damageHitratePhysical):
    clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitratePhysical(builder, damageHitratePhysical)

def clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitrateMagical(builder, damageHitrateMagical):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(damageHitrateMagical), 0)

def AddDamageHitrateMagical(builder, damageHitrateMagical):
    clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitrateMagical(builder, damageHitrateMagical)

def clz_Torappu_EnemyDatabase_AttributesDataAddStunImmune(builder, stunImmune):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(stunImmune), 0)

def AddStunImmune(builder, stunImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddStunImmune(builder, stunImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddSilenceImmune(builder, silenceImmune):
    builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(silenceImmune), 0)

def AddSilenceImmune(builder, silenceImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddSilenceImmune(builder, silenceImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddSleepImmune(builder, sleepImmune):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(sleepImmune), 0)

def AddSleepImmune(builder, sleepImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddSleepImmune(builder, sleepImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddFrozenImmune(builder, frozenImmune):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(frozenImmune), 0)

def AddFrozenImmune(builder, frozenImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddFrozenImmune(builder, frozenImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddLevitateImmune(builder, levitateImmune):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(levitateImmune), 0)

def AddLevitateImmune(builder, levitateImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddLevitateImmune(builder, levitateImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddDisarmedCombatImmune(builder, disarmedCombatImmune):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(disarmedCombatImmune), 0)

def AddDisarmedCombatImmune(builder, disarmedCombatImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddDisarmedCombatImmune(builder, disarmedCombatImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddFearedImmune(builder, fearedImmune):
    builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(fearedImmune), 0)

def AddFearedImmune(builder, fearedImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddFearedImmune(builder, fearedImmune)

def clz_Torappu_EnemyDatabase_AttributesDataAddPalsyImmune(builder, palsyImmune):
    builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(palsyImmune), 0)

def AddPalsyImmune(builder, palsyImmune):
    clz_Torappu_EnemyDatabase_AttributesDataAddPalsyImmune(builder, palsyImmune)

def clz_Torappu_EnemyDatabase_AttributesDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return clz_Torappu_EnemyDatabase_AttributesDataEnd(builder)

import clz_Torappu_Undefinable_1_System_Boolean_
import clz_Torappu_Undefinable_1_System_Int32_
import clz_Torappu_Undefinable_1_System_Single_
try:
    from typing import Optional
except:
    pass

class clz_Torappu_EnemyDatabase_AttributesDataT(object):

    # clz_Torappu_EnemyDatabase_AttributesDataT
    def __init__(self):
        self.maxHp = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.atk = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.def_ = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.magicResistance = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.cost = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.blockCnt = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.moveSpeed = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.attackSpeed = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.baseAttackTime = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.respawnTime = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.hpRecoveryPerSec = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.spRecoveryPerSec = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.maxDeployCount = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.massLevel = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.baseForceLevel = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.tauntLevel = None  # type: Optional[clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T]
        self.epDamageResistance = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.epResistance = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.damageHitratePhysical = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.damageHitrateMagical = None  # type: Optional[clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T]
        self.stunImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.silenceImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.sleepImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.frozenImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.levitateImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.disarmedCombatImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.fearedImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]
        self.palsyImmune = None  # type: Optional[clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzTorappuEnemyDatabaseAttributesData = clz_Torappu_EnemyDatabase_AttributesData()
        clzTorappuEnemyDatabaseAttributesData.Init(buf, pos)
        return cls.InitFromObj(clzTorappuEnemyDatabaseAttributesData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzTorappuEnemyDatabaseAttributesData):
        x = clz_Torappu_EnemyDatabase_AttributesDataT()
        x._UnPack(clzTorappuEnemyDatabaseAttributesData)
        return x

    # clz_Torappu_EnemyDatabase_AttributesDataT
    def _UnPack(self, clzTorappuEnemyDatabaseAttributesData):
        if clzTorappuEnemyDatabaseAttributesData is None:
            return
        if clzTorappuEnemyDatabaseAttributesData.MaxHp() is not None:
            self.maxHp = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.MaxHp())
        if clzTorappuEnemyDatabaseAttributesData.Atk() is not None:
            self.atk = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.Atk())
        if clzTorappuEnemyDatabaseAttributesData.Def() is not None:
            self.def_ = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.Def())
        if clzTorappuEnemyDatabaseAttributesData.MagicResistance() is not None:
            self.magicResistance = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.MagicResistance())
        if clzTorappuEnemyDatabaseAttributesData.Cost() is not None:
            self.cost = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.Cost())
        if clzTorappuEnemyDatabaseAttributesData.BlockCnt() is not None:
            self.blockCnt = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.BlockCnt())
        if clzTorappuEnemyDatabaseAttributesData.MoveSpeed() is not None:
            self.moveSpeed = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.MoveSpeed())
        if clzTorappuEnemyDatabaseAttributesData.AttackSpeed() is not None:
            self.attackSpeed = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.AttackSpeed())
        if clzTorappuEnemyDatabaseAttributesData.BaseAttackTime() is not None:
            self.baseAttackTime = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.BaseAttackTime())
        if clzTorappuEnemyDatabaseAttributesData.RespawnTime() is not None:
            self.respawnTime = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.RespawnTime())
        if clzTorappuEnemyDatabaseAttributesData.HpRecoveryPerSec() is not None:
            self.hpRecoveryPerSec = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.HpRecoveryPerSec())
        if clzTorappuEnemyDatabaseAttributesData.SpRecoveryPerSec() is not None:
            self.spRecoveryPerSec = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.SpRecoveryPerSec())
        if clzTorappuEnemyDatabaseAttributesData.MaxDeployCount() is not None:
            self.maxDeployCount = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.MaxDeployCount())
        if clzTorappuEnemyDatabaseAttributesData.MassLevel() is not None:
            self.massLevel = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.MassLevel())
        if clzTorappuEnemyDatabaseAttributesData.BaseForceLevel() is not None:
            self.baseForceLevel = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.BaseForceLevel())
        if clzTorappuEnemyDatabaseAttributesData.TauntLevel() is not None:
            self.tauntLevel = clz_Torappu_Undefinable_1_System_Int32_.clz_Torappu_Undefinable_1_System_Int32_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.TauntLevel())
        if clzTorappuEnemyDatabaseAttributesData.EpDamageResistance() is not None:
            self.epDamageResistance = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.EpDamageResistance())
        if clzTorappuEnemyDatabaseAttributesData.EpResistance() is not None:
            self.epResistance = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.EpResistance())
        if clzTorappuEnemyDatabaseAttributesData.DamageHitratePhysical() is not None:
            self.damageHitratePhysical = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.DamageHitratePhysical())
        if clzTorappuEnemyDatabaseAttributesData.DamageHitrateMagical() is not None:
            self.damageHitrateMagical = clz_Torappu_Undefinable_1_System_Single_.clz_Torappu_Undefinable_1_System_Single_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.DamageHitrateMagical())
        if clzTorappuEnemyDatabaseAttributesData.StunImmune() is not None:
            self.stunImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.StunImmune())
        if clzTorappuEnemyDatabaseAttributesData.SilenceImmune() is not None:
            self.silenceImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.SilenceImmune())
        if clzTorappuEnemyDatabaseAttributesData.SleepImmune() is not None:
            self.sleepImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.SleepImmune())
        if clzTorappuEnemyDatabaseAttributesData.FrozenImmune() is not None:
            self.frozenImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.FrozenImmune())
        if clzTorappuEnemyDatabaseAttributesData.LevitateImmune() is not None:
            self.levitateImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.LevitateImmune())
        if clzTorappuEnemyDatabaseAttributesData.DisarmedCombatImmune() is not None:
            self.disarmedCombatImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.DisarmedCombatImmune())
        if clzTorappuEnemyDatabaseAttributesData.FearedImmune() is not None:
            self.fearedImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.FearedImmune())
        if clzTorappuEnemyDatabaseAttributesData.PalsyImmune() is not None:
            self.palsyImmune = clz_Torappu_Undefinable_1_System_Boolean_.clz_Torappu_Undefinable_1_System_Boolean_T.InitFromObj(clzTorappuEnemyDatabaseAttributesData.PalsyImmune())

    # clz_Torappu_EnemyDatabase_AttributesDataT
    def Pack(self, builder):
        if self.maxHp is not None:
            maxHp = self.maxHp.Pack(builder)
        if self.atk is not None:
            atk = self.atk.Pack(builder)
        if self.def_ is not None:
            def_ = self.def_.Pack(builder)
        if self.magicResistance is not None:
            magicResistance = self.magicResistance.Pack(builder)
        if self.cost is not None:
            cost = self.cost.Pack(builder)
        if self.blockCnt is not None:
            blockCnt = self.blockCnt.Pack(builder)
        if self.moveSpeed is not None:
            moveSpeed = self.moveSpeed.Pack(builder)
        if self.attackSpeed is not None:
            attackSpeed = self.attackSpeed.Pack(builder)
        if self.baseAttackTime is not None:
            baseAttackTime = self.baseAttackTime.Pack(builder)
        if self.respawnTime is not None:
            respawnTime = self.respawnTime.Pack(builder)
        if self.hpRecoveryPerSec is not None:
            hpRecoveryPerSec = self.hpRecoveryPerSec.Pack(builder)
        if self.spRecoveryPerSec is not None:
            spRecoveryPerSec = self.spRecoveryPerSec.Pack(builder)
        if self.maxDeployCount is not None:
            maxDeployCount = self.maxDeployCount.Pack(builder)
        if self.massLevel is not None:
            massLevel = self.massLevel.Pack(builder)
        if self.baseForceLevel is not None:
            baseForceLevel = self.baseForceLevel.Pack(builder)
        if self.tauntLevel is not None:
            tauntLevel = self.tauntLevel.Pack(builder)
        if self.epDamageResistance is not None:
            epDamageResistance = self.epDamageResistance.Pack(builder)
        if self.epResistance is not None:
            epResistance = self.epResistance.Pack(builder)
        if self.damageHitratePhysical is not None:
            damageHitratePhysical = self.damageHitratePhysical.Pack(builder)
        if self.damageHitrateMagical is not None:
            damageHitrateMagical = self.damageHitrateMagical.Pack(builder)
        if self.stunImmune is not None:
            stunImmune = self.stunImmune.Pack(builder)
        if self.silenceImmune is not None:
            silenceImmune = self.silenceImmune.Pack(builder)
        if self.sleepImmune is not None:
            sleepImmune = self.sleepImmune.Pack(builder)
        if self.frozenImmune is not None:
            frozenImmune = self.frozenImmune.Pack(builder)
        if self.levitateImmune is not None:
            levitateImmune = self.levitateImmune.Pack(builder)
        if self.disarmedCombatImmune is not None:
            disarmedCombatImmune = self.disarmedCombatImmune.Pack(builder)
        if self.fearedImmune is not None:
            fearedImmune = self.fearedImmune.Pack(builder)
        if self.palsyImmune is not None:
            palsyImmune = self.palsyImmune.Pack(builder)
        clz_Torappu_EnemyDatabase_AttributesDataStart(builder)
        if self.maxHp is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddMaxHp(builder, maxHp)
        if self.atk is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddAtk(builder, atk)
        if self.def_ is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddDef(builder, def_)
        if self.magicResistance is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddMagicResistance(builder, magicResistance)
        if self.cost is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddCost(builder, cost)
        if self.blockCnt is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddBlockCnt(builder, blockCnt)
        if self.moveSpeed is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddMoveSpeed(builder, moveSpeed)
        if self.attackSpeed is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddAttackSpeed(builder, attackSpeed)
        if self.baseAttackTime is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddBaseAttackTime(builder, baseAttackTime)
        if self.respawnTime is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddRespawnTime(builder, respawnTime)
        if self.hpRecoveryPerSec is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddHpRecoveryPerSec(builder, hpRecoveryPerSec)
        if self.spRecoveryPerSec is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddSpRecoveryPerSec(builder, spRecoveryPerSec)
        if self.maxDeployCount is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddMaxDeployCount(builder, maxDeployCount)
        if self.massLevel is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddMassLevel(builder, massLevel)
        if self.baseForceLevel is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddBaseForceLevel(builder, baseForceLevel)
        if self.tauntLevel is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddTauntLevel(builder, tauntLevel)
        if self.epDamageResistance is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddEpDamageResistance(builder, epDamageResistance)
        if self.epResistance is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddEpResistance(builder, epResistance)
        if self.damageHitratePhysical is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitratePhysical(builder, damageHitratePhysical)
        if self.damageHitrateMagical is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddDamageHitrateMagical(builder, damageHitrateMagical)
        if self.stunImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddStunImmune(builder, stunImmune)
        if self.silenceImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddSilenceImmune(builder, silenceImmune)
        if self.sleepImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddSleepImmune(builder, sleepImmune)
        if self.frozenImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddFrozenImmune(builder, frozenImmune)
        if self.levitateImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddLevitateImmune(builder, levitateImmune)
        if self.disarmedCombatImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddDisarmedCombatImmune(builder, disarmedCombatImmune)
        if self.fearedImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddFearedImmune(builder, fearedImmune)
        if self.palsyImmune is not None:
            clz_Torappu_EnemyDatabase_AttributesDataAddPalsyImmune(builder, palsyImmune)
        clzTorappuEnemyDatabaseAttributesData = clz_Torappu_EnemyDatabase_AttributesDataEnd(builder)
        return clzTorappuEnemyDatabaseAttributesData
