# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_Torappu_Undefinable_1_System_Boolean_(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_Torappu_Undefinable_1_System_Boolean_()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_Torappu_Undefinable_1_System_Boolean_(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_Torappu_Undefinable_1_System_Boolean_
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_Torappu_Undefinable_1_System_Boolean_
    def MDefined(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # clz_Torappu_Undefinable_1_System_Boolean_
    def MValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def clz_Torappu_Undefinable_1_System_Boolean_Start(builder):
    builder.StartObject(2)

def Start(builder):
    clz_Torappu_Undefinable_1_System_Boolean_Start(builder)

def clz_Torappu_Undefinable_1_System_Boolean_AddMDefined(builder, mDefined):
    builder.PrependBoolSlot(0, mDefined, 0)

def AddMDefined(builder, mDefined):
    clz_Torappu_Undefinable_1_System_Boolean_AddMDefined(builder, mDefined)

def clz_Torappu_Undefinable_1_System_Boolean_AddMValue(builder, mValue):
    builder.PrependBoolSlot(1, mValue, 0)

def AddMValue(builder, mValue):
    clz_Torappu_Undefinable_1_System_Boolean_AddMValue(builder, mValue)

def clz_Torappu_Undefinable_1_System_Boolean_End(builder):
    return builder.EndObject()

def End(builder):
    return clz_Torappu_Undefinable_1_System_Boolean_End(builder)


class clz_Torappu_Undefinable_1_System_Boolean_T(object):

    # clz_Torappu_Undefinable_1_System_Boolean_T
    def __init__(self):
        self.mDefined = False  # type: bool
        self.mValue = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzTorappuUndefinable1SystemBoolean_ = clz_Torappu_Undefinable_1_System_Boolean_()
        clzTorappuUndefinable1SystemBoolean_.Init(buf, pos)
        return cls.InitFromObj(clzTorappuUndefinable1SystemBoolean_)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzTorappuUndefinable1SystemBoolean_):
        x = clz_Torappu_Undefinable_1_System_Boolean_T()
        x._UnPack(clzTorappuUndefinable1SystemBoolean_)
        return x

    # clz_Torappu_Undefinable_1_System_Boolean_T
    def _UnPack(self, clzTorappuUndefinable1SystemBoolean_):
        if clzTorappuUndefinable1SystemBoolean_ is None:
            return
        self.mDefined = clzTorappuUndefinable1SystemBoolean_.MDefined()
        self.mValue = clzTorappuUndefinable1SystemBoolean_.MValue()

    # clz_Torappu_Undefinable_1_System_Boolean_T
    def Pack(self, builder):
        clz_Torappu_Undefinable_1_System_Boolean_Start(builder)
        clz_Torappu_Undefinable_1_System_Boolean_AddMDefined(builder, self.mDefined)
        clz_Torappu_Undefinable_1_System_Boolean_AddMValue(builder, self.mValue)
        clzTorappuUndefinable1SystemBoolean_ = clz_Torappu_Undefinable_1_System_Boolean_End(builder)
        return clzTorappuUndefinable1SystemBoolean_
