# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_Torappu_LevelData_PredefinedData_PredefinedTokenCard(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def InitialCnt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def Hidden(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def Alias(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def UniEquipIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from clz_Torappu_CharacterData_UniqueEquipPair import clz_Torappu_CharacterData_UniqueEquipPair
            obj = clz_Torappu_CharacterData_UniqueEquipPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def UniEquipIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def UniEquipIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def ShowSpIllust(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def Inst(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from clz_Torappu_CharacterInst_Metadata import clz_Torappu_CharacterInst_Metadata
            obj = clz_Torappu_CharacterInst_Metadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def SkillIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def MainSkillLvl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def SkinId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def TmplId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def OverrideSkillBlackboard(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from clz_Torappu_Blackboard_DataPair import clz_Torappu_Blackboard_DataPair
            obj = clz_Torappu_Blackboard_DataPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def OverrideSkillBlackboardLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard
    def OverrideSkillBlackboardIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStart(builder):
    builder.StartObject(11)

def Start(builder):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStart(builder)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInitialCnt(builder, initialCnt):
    builder.PrependInt32Slot(0, initialCnt, 0)

def AddInitialCnt(builder, initialCnt):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInitialCnt(builder, initialCnt)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddHidden(builder, hidden):
    builder.PrependBoolSlot(1, hidden, 0)

def AddHidden(builder, hidden):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddHidden(builder, hidden)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddAlias(builder, alias):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(alias), 0)

def AddAlias(builder, alias):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddAlias(builder, alias)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddUniEquipIds(builder, uniEquipIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(uniEquipIds), 0)

def AddUniEquipIds(builder, uniEquipIds):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddUniEquipIds(builder, uniEquipIds)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartUniEquipIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartUniEquipIdsVector(builder, numElems):
    return clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartUniEquipIdsVector(builder, numElems)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddShowSpIllust(builder, showSpIllust):
    builder.PrependBoolSlot(4, showSpIllust, 0)

def AddShowSpIllust(builder, showSpIllust):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddShowSpIllust(builder, showSpIllust)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInst(builder, inst):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(inst), 0)

def AddInst(builder, inst):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInst(builder, inst)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkillIndex(builder, skillIndex):
    builder.PrependInt32Slot(6, skillIndex, 0)

def AddSkillIndex(builder, skillIndex):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkillIndex(builder, skillIndex)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddMainSkillLvl(builder, mainSkillLvl):
    builder.PrependInt32Slot(7, mainSkillLvl, 0)

def AddMainSkillLvl(builder, mainSkillLvl):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddMainSkillLvl(builder, mainSkillLvl)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkinId(builder, skinId):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(skinId), 0)

def AddSkinId(builder, skinId):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkinId(builder, skinId)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddTmplId(builder, tmplId):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(tmplId), 0)

def AddTmplId(builder, tmplId):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddTmplId(builder, tmplId)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddOverrideSkillBlackboard(builder, overrideSkillBlackboard):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(overrideSkillBlackboard), 0)

def AddOverrideSkillBlackboard(builder, overrideSkillBlackboard):
    clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddOverrideSkillBlackboard(builder, overrideSkillBlackboard)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartOverrideSkillBlackboardVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOverrideSkillBlackboardVector(builder, numElems):
    return clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartOverrideSkillBlackboardVector(builder, numElems)

def clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardEnd(builder):
    return builder.EndObject()

def End(builder):
    return clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardEnd(builder)

import clz_Torappu_Blackboard_DataPair
import clz_Torappu_CharacterData_UniqueEquipPair
import clz_Torappu_CharacterInst_Metadata
try:
    from typing import List, Optional
except:
    pass

class clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardT(object):

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardT
    def __init__(self):
        self.initialCnt = 0  # type: int
        self.hidden = False  # type: bool
        self.alias = None  # type: str
        self.uniEquipIds = None  # type: List[clz_Torappu_CharacterData_UniqueEquipPair.clz_Torappu_CharacterData_UniqueEquipPairT]
        self.showSpIllust = False  # type: bool
        self.inst = None  # type: Optional[clz_Torappu_CharacterInst_Metadata.clz_Torappu_CharacterInst_MetadataT]
        self.skillIndex = 0  # type: int
        self.mainSkillLvl = 0  # type: int
        self.skinId = None  # type: str
        self.tmplId = None  # type: str
        self.overrideSkillBlackboard = None  # type: List[clz_Torappu_Blackboard_DataPair.clz_Torappu_Blackboard_DataPairT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzTorappuLevelDataPredefinedDataPredefinedTokenCard = clz_Torappu_LevelData_PredefinedData_PredefinedTokenCard()
        clzTorappuLevelDataPredefinedDataPredefinedTokenCard.Init(buf, pos)
        return cls.InitFromObj(clzTorappuLevelDataPredefinedDataPredefinedTokenCard)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzTorappuLevelDataPredefinedDataPredefinedTokenCard):
        x = clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardT()
        x._UnPack(clzTorappuLevelDataPredefinedDataPredefinedTokenCard)
        return x

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardT
    def _UnPack(self, clzTorappuLevelDataPredefinedDataPredefinedTokenCard):
        if clzTorappuLevelDataPredefinedDataPredefinedTokenCard is None:
            return
        self.initialCnt = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.InitialCnt()
        self.hidden = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.Hidden()
        self.alias = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.Alias()
        if not clzTorappuLevelDataPredefinedDataPredefinedTokenCard.UniEquipIdsIsNone():
            self.uniEquipIds = []
            for i in range(clzTorappuLevelDataPredefinedDataPredefinedTokenCard.UniEquipIdsLength()):
                if clzTorappuLevelDataPredefinedDataPredefinedTokenCard.UniEquipIds(i) is None:
                    self.uniEquipIds.append(None)
                else:
                    clz_Torappu_CharacterData_UniqueEquipPair_ = clz_Torappu_CharacterData_UniqueEquipPair.clz_Torappu_CharacterData_UniqueEquipPairT.InitFromObj(clzTorappuLevelDataPredefinedDataPredefinedTokenCard.UniEquipIds(i))
                    self.uniEquipIds.append(clz_Torappu_CharacterData_UniqueEquipPair_)
        self.showSpIllust = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.ShowSpIllust()
        if clzTorappuLevelDataPredefinedDataPredefinedTokenCard.Inst() is not None:
            self.inst = clz_Torappu_CharacterInst_Metadata.clz_Torappu_CharacterInst_MetadataT.InitFromObj(clzTorappuLevelDataPredefinedDataPredefinedTokenCard.Inst())
        self.skillIndex = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.SkillIndex()
        self.mainSkillLvl = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.MainSkillLvl()
        self.skinId = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.SkinId()
        self.tmplId = clzTorappuLevelDataPredefinedDataPredefinedTokenCard.TmplId()
        if not clzTorappuLevelDataPredefinedDataPredefinedTokenCard.OverrideSkillBlackboardIsNone():
            self.overrideSkillBlackboard = []
            for i in range(clzTorappuLevelDataPredefinedDataPredefinedTokenCard.OverrideSkillBlackboardLength()):
                if clzTorappuLevelDataPredefinedDataPredefinedTokenCard.OverrideSkillBlackboard(i) is None:
                    self.overrideSkillBlackboard.append(None)
                else:
                    clz_Torappu_Blackboard_DataPair_ = clz_Torappu_Blackboard_DataPair.clz_Torappu_Blackboard_DataPairT.InitFromObj(clzTorappuLevelDataPredefinedDataPredefinedTokenCard.OverrideSkillBlackboard(i))
                    self.overrideSkillBlackboard.append(clz_Torappu_Blackboard_DataPair_)

    # clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardT
    def Pack(self, builder):
        if self.alias is not None:
            alias = builder.CreateString(self.alias)
        if self.uniEquipIds is not None:
            uniEquipIdslist = []
            for i in range(len(self.uniEquipIds)):
                uniEquipIdslist.append(self.uniEquipIds[i].Pack(builder))
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartUniEquipIdsVector(builder, len(self.uniEquipIds))
            for i in reversed(range(len(self.uniEquipIds))):
                builder.PrependUOffsetTRelative(uniEquipIdslist[i])
            uniEquipIds = builder.EndVector()
        if self.inst is not None:
            inst = self.inst.Pack(builder)
        if self.skinId is not None:
            skinId = builder.CreateString(self.skinId)
        if self.tmplId is not None:
            tmplId = builder.CreateString(self.tmplId)
        if self.overrideSkillBlackboard is not None:
            overrideSkillBlackboardlist = []
            for i in range(len(self.overrideSkillBlackboard)):
                overrideSkillBlackboardlist.append(self.overrideSkillBlackboard[i].Pack(builder))
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStartOverrideSkillBlackboardVector(builder, len(self.overrideSkillBlackboard))
            for i in reversed(range(len(self.overrideSkillBlackboard))):
                builder.PrependUOffsetTRelative(overrideSkillBlackboardlist[i])
            overrideSkillBlackboard = builder.EndVector()
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardStart(builder)
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInitialCnt(builder, self.initialCnt)
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddHidden(builder, self.hidden)
        if self.alias is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddAlias(builder, alias)
        if self.uniEquipIds is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddUniEquipIds(builder, uniEquipIds)
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddShowSpIllust(builder, self.showSpIllust)
        if self.inst is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddInst(builder, inst)
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkillIndex(builder, self.skillIndex)
        clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddMainSkillLvl(builder, self.mainSkillLvl)
        if self.skinId is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddSkinId(builder, skinId)
        if self.tmplId is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddTmplId(builder, tmplId)
        if self.overrideSkillBlackboard is not None:
            clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardAddOverrideSkillBlackboard(builder, overrideSkillBlackboard)
        clzTorappuLevelDataPredefinedDataPredefinedTokenCard = clz_Torappu_LevelData_PredefinedData_PredefinedTokenCardEnd(builder)
        return clzTorappuLevelDataPredefinedDataPredefinedTokenCard
