# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class enum__Torappu_LevelData_WaveData_FragmentData_ActionData_RandomType(object):
    ALWAYS = 0
    PER_DAY = 1
    NEVER = 2
    PER_SETTLE_DAY = 3
    PER_SEASON = 4
