# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class clz_UnityEngine_Vector2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = clz_UnityEngine_Vector2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsclz_UnityEngine_Vector2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # clz_UnityEngine_Vector2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # clz_UnityEngine_Vector2
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # clz_UnityEngine_Vector2
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def clz_UnityEngine_Vector2Start(builder):
    builder.StartObject(2)

def Start(builder):
    clz_UnityEngine_Vector2Start(builder)

def clz_UnityEngine_Vector2AddX(builder, x):
    builder.PrependFloat32Slot(0, x, 0.0)

def AddX(builder, x):
    clz_UnityEngine_Vector2AddX(builder, x)

def clz_UnityEngine_Vector2AddY(builder, y):
    builder.PrependFloat32Slot(1, y, 0.0)

def AddY(builder, y):
    clz_UnityEngine_Vector2AddY(builder, y)

def clz_UnityEngine_Vector2End(builder):
    return builder.EndObject()

def End(builder):
    return clz_UnityEngine_Vector2End(builder)


class clz_UnityEngine_Vector2T(object):

    # clz_UnityEngine_Vector2T
    def __init__(self):
        self.x = 0.0  # type: float
        self.y = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clzUnityEngineVector2 = clz_UnityEngine_Vector2()
        clzUnityEngineVector2.Init(buf, pos)
        return cls.InitFromObj(clzUnityEngineVector2)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clzUnityEngineVector2):
        x = clz_UnityEngine_Vector2T()
        x._UnPack(clzUnityEngineVector2)
        return x

    # clz_UnityEngine_Vector2T
    def _UnPack(self, clzUnityEngineVector2):
        if clzUnityEngineVector2 is None:
            return
        self.x = clzUnityEngineVector2.X()
        self.y = clzUnityEngineVector2.Y()

    # clz_UnityEngine_Vector2T
    def Pack(self, builder):
        clz_UnityEngine_Vector2Start(builder)
        clz_UnityEngine_Vector2AddX(builder, self.x)
        clz_UnityEngine_Vector2AddY(builder, self.y)
        clzUnityEngineVector2 = clz_UnityEngine_Vector2End(builder)
        return clzUnityEngineVector2
