# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class enum__Torappu_EvolvePhase(object):
    PHASE_0 = 0
    PHASE_1 = 1
    PHASE_2 = 2
    PHASE_3 = 3
    E_NUM = 4
